name: voipadmin
services:
  minio:
    container_name: voip-admin-minio
    image: minio/minio:latest
    #    restart: "unless-stopped"
    restart: always
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    # Allow all incoming hosts to access the server by using 0.0.0.0
    command: server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3
